### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by blacksmoke26** [mfix22/graphql-error-parser#1]
Can I use it in production?

**Comment by mfix22** [comment]
Hi @blacksmoke26 👋I still maintain this package, so I can fix issues if you find them. However, it was built with a very specify use case in mind (see [tests for use cases](https://github.com/mfix22/graphql-error-parser/blob/master/index.spec.js)).

**Comment by blacksmoke26** [comment]
Thank you! Will use in time!
